import { AppointmentRecord, AvailableSlot, ScenarioChip, PilotKpis } from "./types";

export const APPOINTMENTS: AppointmentRecord[] = [
  {
    patientId: "PT-1042",
    patientName: "Maria Lopez",
    appointmentId: "APT-5001",
    appointmentDateTime: "2026-07-08T15:00:00",
    location: "Pinecrest Infusion Center — Chair 4",
    serviceType: "IV Hydration",
    careNeed: "Dehydration / oncology supportive care",
    icd10Code: "E86.0",
    icd10Description: "Dehydration",
    cptFamily: "96360 / 96361",
    expectedDurationMinutes: 45,
    appointmentStatus: "Upcoming",
    triggerReason: "No confirmation received",
    riskLevel: "Medium",
    communicationPreference: "SMS",
    preferredLanguage: "Spanish",
    consentSms: true,
    consentVoice: true,
    consentEmail: true,
    consentVideo: false,
    source: "EHR",
    lastContacted: "Never",
    age: 54,
  },
  {
    patientId: "PT-1043",
    patientName: "James Carter",
    appointmentId: "APT-5002",
    appointmentDateTime: "2026-07-09T10:30:00",
    location: "Pinecrest Infusion Center — Chair 2",
    serviceType: "IV Iron Infusion",
    careNeed: "Iron-deficiency anemia",
    icd10Code: "D50.9",
    icd10Description: "Iron deficiency anemia, unspecified",
    cptFamily: "96365",
    drugCode: "J1756 / J1439 / Q0138",
    expectedDurationMinutes: 60,
    appointmentStatus: "Upcoming",
    triggerReason: "Prep confirmation needed",
    riskLevel: "Low",
    communicationPreference: "SMS",
    preferredLanguage: "English",
    consentSms: true,
    consentVoice: true,
    consentEmail: true,
    consentVideo: false,
    source: "EHR",
    lastContacted: "3 days ago",
    age: 67,
  },
  {
    patientId: "PT-1044",
    patientName: "Linda Nguyen",
    appointmentId: "APT-5003",
    appointmentDateTime: "2026-07-10T09:00:00",
    location: "Pinecrest Infusion Center — Chair 1",
    serviceType: "Chemotherapy IV Infusion",
    careNeed: "Malignant neoplasm treatment",
    icd10Code: "C50.911",
    icd10Description: "Malignant neoplasm of unspecified site of right female breast",
    cptFamily: "96413 / 96415",
    expectedDurationMinutes: 180,
    appointmentStatus: "Upcoming",
    triggerReason: "No response after initial reminder",
    riskLevel: "High",
    communicationPreference: "Voice",
    preferredLanguage: "English",
    consentSms: true,
    consentVoice: true,
    consentEmail: true,
    consentVideo: true,
    source: "EHR",
    lastContacted: "1 week ago",
    age: 61,
  },
  {
    patientId: "PT-1045",
    patientName: "Robert Miller",
    appointmentId: "APT-5004",
    appointmentDateTime: "2026-07-07T08:00:00",
    location: "Pinecrest Infusion Center — Chair 3",
    serviceType: "Blood Transfusion",
    careNeed: "Anemia due to chronic disease",
    icd10Code: "D63.8",
    icd10Description: "Anemia in other chronic diseases classified elsewhere",
    cptFamily: "36430",
    expectedDurationMinutes: 120,
    appointmentStatus: "No Show",
    triggerReason: "Rebooking recovery needed",
    riskLevel: "High",
    communicationPreference: "SMS",
    preferredLanguage: "English",
    consentSms: true,
    consentVoice: false,
    consentEmail: true,
    consentVideo: false,
    source: "EHR",
    lastContacted: "2 days ago",
    age: 71,
  },
  {
    patientId: "PT-1046",
    patientName: "Priya Shah",
    appointmentId: "APT-5005",
    appointmentDateTime: "2026-07-11T14:15:00",
    location: "Pinecrest Infusion Center — Chair 5",
    serviceType: "Biologic Infusion",
    careNeed: "Crohn's disease",
    icd10Code: "K50.90",
    icd10Description: "Crohn's disease of small intestine, without complications",
    cptFamily: "96365 / 96366",
    drugCode: "J1745 / J3380 / J3358",
    expectedDurationMinutes: 90,
    appointmentStatus: "Upcoming",
    triggerReason: "Barrier check needed",
    riskLevel: "Medium",
    communicationPreference: "Email",
    preferredLanguage: "English",
    consentSms: true,
    consentVoice: true,
    consentEmail: true,
    consentVideo: true,
    source: "EHR",
    lastContacted: "5 days ago",
    age: 38,
  },
];

export const AVAILABLE_SLOTS: AvailableSlot[] = [
  {
    slotId: "SLT-001",
    dateTime: "2026-07-08T15:00:00",
    label: "Tuesday, Jul 8 · 3:00 PM",
    location: "Pinecrest Infusion Center",
    serviceTypeSupported: "All",
    durationMinutes: 60,
    chairOrResource: "Infusion Chair 4",
    staffApprovalRequired: false,
    status: "Available",
  },
  {
    slotId: "SLT-002",
    dateTime: "2026-07-09T10:30:00",
    label: "Wednesday, Jul 9 · 10:30 AM",
    location: "Pinecrest Infusion Center",
    serviceTypeSupported: "All",
    durationMinutes: 60,
    chairOrResource: "Infusion Chair 2",
    staffApprovalRequired: false,
    status: "Available",
  },
  {
    slotId: "SLT-003",
    dateTime: "2026-07-10T14:15:00",
    label: "Thursday, Jul 10 · 2:15 PM",
    location: "Pinecrest Infusion Center",
    serviceTypeSupported: "All",
    durationMinutes: 60,
    chairOrResource: "Infusion Chair 1",
    staffApprovalRequired: true,
    status: "Available",
  },
];

export const SCENARIOS: ScenarioChip[] = [
  {
    id: "accept_slot",
    label: "Accept First Slot",
    patientMessage: "Yes, Tuesday works.",
    agentResponse:
      "Great. I'll mark Tuesday at 3:00 PM as accepted. Pinecrest Care will confirm your appointment shortly.",
    intent: "Accepted appointment",
    sentiment: "Positive",
    actionTriggered: "Create rebooking task",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'Yes, Tuesday works.'" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Accepted first available slot", metadata: { intent: "accept_slot" } },
      { eventType: "REBOOKING_TASK_CREATED", description: "Rebooking task created for Tuesday 3:00 PM — staff approval not required" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Rebooking recovery +1 · Confirmed visits pending" },
    ],
  },
  {
    id: "reject_slot",
    label: "Reject First Slot",
    patientMessage: "No, Wednesday morning is better.",
    agentResponse:
      "Got it. The next available option is Wednesday at 10:30 AM. Would that work for you?",
    intent: "Alternative preference",
    reasonCategory: "Schedule conflict",
    sentiment: "Neutral",
    actionTriggered: "Check alternative slot / create staff task",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'No, Wednesday morning is better.'" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Alternative slot preference", metadata: { intent: "reject_slot" } },
      { eventType: "REASON_CAPTURED", description: "Reason captured: Schedule conflict — requested Wednesday morning" },
      { eventType: "SLOT_IDENTIFIED", description: "Next available slot identified: Wednesday, Jul 9 · 10:30 AM — Chair 2" },
      { eventType: "REBOOKING_TASK_CREATED", description: "Rebooking preference sent to scheduling team — staff approval pending" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Reason capture +1" },
    ],
  },
  {
    id: "schedule_conflict",
    label: "Schedule Conflict",
    patientMessage: "I have work. I can't make it Tuesday.",
    agentResponse:
      "No problem. The next available option is Wednesday at 10:30 AM. Would that work for you?",
    intent: "Schedule conflict",
    reasonCategory: "Work / schedule conflict",
    sentiment: "Neutral",
    actionTriggered: "Offer next available slot",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'I have work. I can't make it Tuesday.'" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Schedule conflict", metadata: { intent: "schedule_conflict" } },
      { eventType: "REASON_CAPTURED", description: "Reason captured: Work / schedule conflict" },
      { eventType: "SLOT_IDENTIFIED", description: "Alternative slot identified: Wednesday, Jul 9 · 10:30 AM" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Reason capture +1" },
    ],
  },
  {
    id: "transportation",
    label: "Transportation Barrier",
    patientMessage: "I don't have a ride.",
    agentResponse:
      "Thanks for letting us know. I'll note transportation as a barrier. Would a different appointment time help, or would you like Pinecrest staff to follow up with you?",
    intent: "Transportation barrier",
    reasonCategory: "Transportation",
    sentiment: "Neutral",
    actionTriggered: "Offer rebooking or staff follow-up",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'I don't have a ride.'" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Transportation barrier", metadata: { intent: "transportation" } },
      { eventType: "REASON_CAPTURED", description: "Reason captured: Transportation — no ride available" },
      { eventType: "STAFF_ESCALATION_CREATED", description: "Staff task created: Transportation barrier follow-up" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Reason capture +1 · Staff task created" },
    ],
  },
  {
    id: "billing",
    label: "Billing Question",
    patientMessage: "How much will this cost? Is this covered by insurance?",
    agentResponse:
      "I'm not able to confirm your exact cost here, but I'll route this to Pinecrest's patient access team for follow-up. Would you like someone to contact you about your coverage?",
    intent: "Billing / cost concern",
    sentiment: "Neutral",
    actionTriggered: "Create patient access follow-up task",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'How much will this cost? Is this covered by insurance?'" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Billing / cost concern — outside agent scope", metadata: { intent: "billing" } },
      { eventType: "BILLING_HANDOFF", description: "Routing to patient access / financial counselor team" },
      { eventType: "STAFF_ESCALATION_CREATED", description: "Patient access task created: Cost / coverage question for this appointment" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Human handoff required" },
    ],
  },
  {
    id: "clinical",
    label: "Clinical Question",
    guardrail: true,
    patientMessage: "I feel sick. Should I still come in?",
    agentResponse:
      "I'm sorry you're not feeling well. I can't give medical advice by text, but I'll route this to the Pinecrest clinical team so they can follow up with you. If this feels urgent or severe, please call your care team directly or seek urgent care.",
    intent: "Clinical concern",
    sentiment: "Negative",
    actionTriggered: "Escalate to clinical team",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'I feel sick. Should I still come in?'" },
      { eventType: "INTENT_CLASSIFIED", description: "⚠ GUARDRAIL — Intent: Clinical concern. Agent does NOT answer. Hard stop.", metadata: { intent: "clinical", guardrail: "true" } },
      { eventType: "CLINICAL_ESCALATION", description: "Escalating to Pinecrest clinical team with full context — SLA: callback within 2 hours" },
      { eventType: "STAFF_ESCALATION_CREATED", description: "Clinical review task created — agent conversation paused pending clinical response" },
    ],
  },
  {
    id: "language",
    label: "Language Switch",
    patientMessage: "¿Pueden escribirme en español?",
    agentResponse:
      "¡Por supuesto! Continuaremos en español. Le confirmamos su cita en Pinecrest Care. ¿Le funciona el martes a las 3:00 PM?",
    intent: "Language preference",
    sentiment: "Positive",
    actionTriggered: "Update preferred language — continue in Spanish",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied in Spanish — language switch requested" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Language preference — Spanish", metadata: { intent: "language", language: "es" } },
      { eventType: "LANGUAGE_UPDATED", description: "Preferred language updated to Spanish — continuing outreach in es" },
      { eventType: "MESSAGE_SENT", description: "Spanish-language confirmation message sent using approved translated script" },
    ],
  },
  {
    id: "no_response",
    label: "No Response",
    patientMessage: "(no reply after first outreach)",
    agentResponse:
      "Hi, this is Pinecrest Care following up. We haven't heard back about your upcoming appointment. Tuesday at 3:00 PM is still available. Reply YES to confirm or call us at your convenience.",
    intent: "No response",
    sentiment: "Neutral",
    actionTriggered: "Schedule follow-up SMS in 12 hours",
    traceEvents: [
      { eventType: "MESSAGE_SENT", description: "Initial outreach delivered — no response within 12-hour window" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: No response — escalate channel per preference + consent" },
      { eventType: "FOLLOW_UP_SCHEDULED", description: "Follow-up SMS scheduled in 12 hours" },
      { eventType: "STAFF_ESCALATION_CREATED", description: "If no response after second attempt: escalate to AI voice call or staff task based on risk level" },
    ],
  },
  {
    id: "wrong_number",
    label: "Wrong Number",
    patientMessage: "Wrong number.",
    agentResponse:
      "Thank you for letting us know. We'll stop messages to this number and flag the contact information for review by Pinecrest Care.",
    intent: "Wrong number",
    sentiment: "Neutral",
    actionTriggered: "Suppress outreach and flag data quality issue",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'Wrong number.'" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Wrong number — suppress outreach immediately", metadata: { intent: "wrong_number" } },
      { eventType: "WRONG_NUMBER_FLAGGED", description: "Contact record flagged for data quality review — outreach suppressed" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Data quality flag +1" },
    ],
  },
  {
    id: "opt_out",
    label: "Opt Out",
    patientMessage: "Stop.",
    agentResponse:
      "You've been opted out of text messages from Pinecrest Care. Please contact Pinecrest directly for appointment questions.",
    intent: "Opt-out",
    sentiment: "Negative",
    actionTriggered: "Update communication preference — SMS suppressed",
    traceEvents: [
      { eventType: "PATIENT_RESPONSE_RECEIVED", description: "Patient replied: 'Stop.' — opt-out keyword detected" },
      { eventType: "INTENT_CLASSIFIED", description: "Intent: Opt-out — TCPA compliance action required immediately", metadata: { intent: "opt_out" } },
      { eventType: "OPT_OUT_RECORDED", description: "Communication preference updated: SMS suppressed per TCPA" },
      { eventType: "KPI_UPDATED", description: "KPI updated: Opt-out rate tracked — within guardrail target (<3%)" },
    ],
  },
];

export const PILOT_KPIS: PilotKpis = {
  totalPatients: 420,
  sameDayLeakageRate: 11.4,
  baselineLeakageRate: 21.2,
  controlLeakageRate: 18.9,
  confirmationRate: 71,
  pendingRate: 18,
  noResponseRate: 11,
  reasonCaptureRate: 63,
  rebookingAttempts: 148,
  rebookingAccepted: 110,
  rebookingCompleted: 89,
  completedVisits: 176,
  automatedPatientActions: 312,
  avgMinutesSavedPerAction: 30,
  staffTimeSavedHours: 156,
  sentimentPositivePct: 58,
  sentimentNeutralPct: 34,
  sentimentNegativePct: 8,
};

export const REASON_BREAKDOWN: { reason: string; count: number; color: string }[] = [
  { reason: "No documented reason", count: 41, color: "var(--faint)" },
  { reason: "Schedule conflict", count: 28, color: "var(--blue)" },
  { reason: "Transportation", count: 19, color: "var(--amber)" },
  { reason: "Not feeling well", count: 16, color: "var(--accent)" },
  { reason: "Work / family obligation", count: 14, color: "#7c3aed" },
  { reason: "Cost / insurance concern", count: 11, color: "var(--green)" },
  { reason: "Prep confusion", count: 7, color: "#0891b2" },
  { reason: "Clinical concern", count: 6, color: "var(--accent)" },
  { reason: "Wrong number / bad contact", count: 5, color: "var(--muted)" },
  { reason: "Opt-out", count: 3, color: "var(--faint)" },
];
